---
version: "3.3"

services:
  iosxe:
    hostname: cisco_iosxe
    privileged: true
    image: scrapli-cisco-iosxe
    networks:
      net1:
        ipv4_address: 172.18.0.11

  nxos:
    hostname: cisco_nxos
    privileged: true
    image: scrapli-cisco-nxos
    networks:
      net1:
        ipv4_address: 172.18.0.12

  iosxr:
    hostname: cisco_iosxr
    privileged: true
    image: scrapli-cisco-iosxr
    networks:
      net1:
        ipv4_address: 172.18.0.13

  eos:
    hostname: arista_eos
    privileged: true
    image: scrapli-arista-eos
    networks:
      net1:
        ipv4_address: 172.18.0.14

  junos:
    hostname: juniper_junos
    privileged: true
    image: scrapli-juniper-junos
    networks:
      net1:
        ipv4_address: 172.18.0.15

  linux:
    hostname: linux
    image: dbarroso/stupid_ssh_container
    networks:
      net1:
        ipv4_address: 172.18.0.20

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/26
    driver_opts:
      com.docker.network.bridge.name: br_scrapli

