---
name: libscrapli

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.zig-triple }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-triple:
          - x86_64-macos
          - aarch64-macos
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - aarch64-linux-gnu
          - aarch64-linux-musl

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"

      - name: load target libscrapli version
        run: |
          VERSION=$(grep -Eo 'LIBSCRAPLI_VERSION\s*=\s*\"[^\"]+\"' setup.py | cut -d '"' -f2)
          if echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+(-[a-z]+\.[0-9]+)?$'; then
            VERSION="v$VERSION"
          fi
          echo "LIBSCRAPLI_TAG_OR_HASH=$VERSION" >> "$GITHUB_ENV"

      - name: load target libscrapli out file name
        run: |
          if [[ "$TARGET" == *linux* ]]; then
              EXT="so"
          else
              EXT="dylib"
          fi

          STRIPPED_TAG_OR_HASH="${LIBSCRAPLI_TAG_OR_HASH#v}"
          echo "LIBSCRAPLI_OUT_NAME=${{ matrix.zig-triple }}-libscrapli.${STRIPPED_TAG_OR_HASH}.${EXT}" >> "$GITHUB_ENV"

      - name: run builder image
        run: |
          docker run --rm \
            -v "${PWD}/out:/out" \
            -e TAG="${{ env.LIBSCRAPLI_TAG_OR_HASH }}" \
            -e TARGET="${{ matrix.zig-triple }}" \
            -e OUT_NAME="${{ env.LIBSCRAPLI_OUT_NAME }}" \
            ghcr.io/scrapli/libscrapli/builder:latest

      - name: upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.LIBSCRAPLI_OUT_NAME }}"
          path: "out/${{ env.LIBSCRAPLI_OUT_NAME }}"
