---
name: validate

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  validate-legacy:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        # test every target we can easily do in ci
        os: ["ubuntu-latest", "macos-latest", "ubuntu-24.04-arm"]

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dynamically linked libscrapli dependencies
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            brew install coreutils pcre2 libssh2
          elif [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libpcre2-dev libssh2-1-dev
          fi

      - name: set release version
        run: |
          set -euo pipefail

          RELEASE_TAG="${{ github.ref_name }}"
          RELEASE_VERSION="${RELEASE_TAG#v}"

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

          PRERELEASE=""

          if [[ "$RELEASE_VERSION" =~ -rc\.([0-9]+)$ ]]; then
            PRERELEASE="rc${BASH_REMATCH[1]}"
          elif [[ "$RELEASE_VERSION" =~ -beta\.([0-9]+)$ ]]; then
            PRERELEASE="b${BASH_REMATCH[1]}"
          elif [[ "$RELEASE_VERSION" =~ -alpha\.([0-9]+)$ ]]; then
            PRERELEASE="a${BASH_REMATCH[1]}"
          fi

          CALVER="$(date +'%Y.%m.%d')"

          if [[ -n "$PRERELEASE" ]]; then
            CALVER="${CALVER}${PRERELEASE}"
          fi

          echo "CALENDAR_VERSION=$CALVER" >> "$GITHUB_ENV"

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"

      - name: install and test dynamic libscrapli (from source - no wheel provided for dynamic)
        run: |
          LIBSCRAPLI_DYNAMIC=true python -m pip install .
          python -c "from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()"

      - name: remove checked out scrapli and uninstall dynamically linked scrapli
        run: |
            rm -rf scrapli
            pip uninstall scrapli scrapli2 --yes

      - name: install scrapli (retrying for pypi) and load ffi mapping
        run: |
          set -euo pipefail

          timeout=300
          start=$(date +%s)

          while true; do
            if python -m pip install "scrapli==${{ env.CALENDAR_VERSION }}"; then
              break
            fi

            now=$(date +%s)
            if (( now - start > timeout )); then
              echo "timed out waiting for nrew release to appear on pypi"
              exit 1
            fi

            sleep 15
          done

      - name: test load ffi mapping in installed scrapli
        run: |
          python -c "from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()"

  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # test every target we can easily do in ci
        os: ["ubuntu-latest", "macos-latest", "ubuntu-24.04-arm"]

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dynamically linked libscrapli dependencies
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            brew install coreutils pcre2 libssh2
          elif [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libpcre2-dev libssh2-1-dev
          fi

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          RELEASE_VERSION=$(echo "$RELEASE_VERSION" | sed -E 's/-rc\.?([0-9]+)/rc\1/')

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: load env vars for workflow run
        run: |
          source .github/vars.env
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"

      - name: install and test dynamic libscrapli (from source - no wheel provided for dynamic)
        run: |
          LIBSCRAPLI_DYNAMIC=true python -m pip install .
          python -c "from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()"

      - name: remove checked out scrapli and uninstall dynamically linked scrapli
        run: |
            rm -rf scrapli
            pip uninstall scrapli scrapli2 --yes

      - name: install scrapli (retrying for pypi) and load ffi mapping
        run: |
          set -euo pipefail

          timeout=300
          start=$(date +%s)

          while true; do
            if python -m pip install "scrapli2==${{ env.RELEASE_VERSION }}"; then
              break
            fi

            now=$(date +%s)
            if (( now - start > timeout )); then
              echo "timed out waiting for nrew release to appear on pypi"
              exit 1
            fi

            sleep 15
          done

      - name: test load ffi mapping in installed scrapli
        run: |
          python -c "from scrapli.ffi_mapping import LibScrapliMapping; LibScrapliMapping()"
